// usMap.idl : usMap 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(usMap.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(288BBDFD-3F13-4AEC-851C-256E044085F4),
	version(1.0),
	helpstring("usMap 1.0 类型库")
]
library usMapLib
{
	importlib("stdole2.tlb");
};
