/* Generated by Together */

#ifndef CMARKERFILLSYMBOL_H
#define CMARKERFILLSYMBOL_H
#include "IFillSymbol.h"
#include "SimpleMarkerSymbol.h"
#include "CDC.h"
#include "IArchive.h"

namespace Display{
class DISPLAY_DLL CMarkerFillSymbol : public IFillSymbol 
{
public:
		CMarkerFillSymbol();

		CMarkerFillSymbol(const CMarkerFillSymbol& toMarkFillSymbol);

		CMarkerFillSymbol& operator = (const CMarkerFillSymbol& toMarkFillSymbol);

		~CMarkerFillSymbol();
	
		void SetOffsetXY( float OffsetX , float OffsetY);//设置偏移
		
		void SetSeparationXY( float SeparationX , float SeparationY );//设置间隔
		
		float GetOffsetX() ;

		float GetOffsetY();//得到偏移
		
		float GetSeparationX();  //得到间隔
		
		float GetSeparationY();  

		void SetMarkSymbol(IMarkerSymbolPtr makeSymbol );//设置点符号
		

		IMarkerSymbolPtr GetMarkSymbol();
		void SetMarkFillRand(bool brand);//设置是否以随机填充面
		

		bool GetMarkFillRand( );//得到是否以随机数填充面
		

		virtual void Draw(void * pObject );        //绘制函数 
		

		virtual SYMBOL_TYPE GetType();		//得到类类型，抽象方法，子类须实现	
		

		virtual void SelectDC(Display::CDC *pDC);			//装配画布，抽象方法，子类须实现
		

		virtual void SetReadyDraw();			//设置当前符号为可画	
		

		void SetFillColor(unsigned long color);//设置符号颜色
		
		unsigned long GetFillColor();//得到符号颜色

		virtual void SetProperties(const char* PropertyName,const _variant_t& PropertyValue);

		virtual _variant_t GetProperties( const char* PropertyName );			//得到当前符号的属性配置

		virtual void Zoom(float rate);

		virtual void ClearDC();

protected:
	virtual void OnUnitChanged(SYSTEM::SYS_UNIT_TYPE oldUnit , SYSTEM::SYS_UNIT_TYPE newUnit);
	virtual void OnChangingInSelectDC();

private:
		IMarkerSymbolPtr m_pMSfill;  
		long m_OffsetX,m_OffsetY; 
		float m_fOffsetX , m_fOffsetY;
		long m_SeparationX,m_SeparationY;
		float m_fSeparationX , m_fSeparationY;
		bool m_brand; //是否会之随机点
public:

        virtual void serialization(SYSTEM::IArchive & ar);
};

typedef SYSTEM::CSmartPtr<CMarkerFillSymbol> IMarkerFillSymbolPtr;
}
#endif //CMARKFILLSYMBOL_H
