//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Control.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDD_DIALOG_FUZZYKMEAN           167
#define IDC_RADIO_EXPORT_ALL            1053
#define IDC_RADIO_EXPOERT_SELECTED      1054
#define IDC_EDIT_INPUTFILE              1055
#define IDC_BUTTON_INPUTFILE            1056
#define IDC_EDIT_OUTPUTFILE             1057
#define IDC_BUTTON_OUTPUTFILE           1058
#define IDC_EDIT_CLASSNUM               1059
#define IDC_EDIT_SAMPLECOUNT            1060
#define IDC_COMBO_Export                1061
#define IDC_EDIT_ITERCOUNT              1062
#define IDC_EDIT_THREOLD                1063
#define IDC_PAN                         2000
#define IDC_PROGRESS                    2001
#define IDC_ZOOMIN                      2002
#define IDC_PROGRESS_TITLE              2003
#define IDC_ZOOMOUT                     2004
#define IDC_EDIT_LAYERNAME              2005
#define IDC_Cross                       2006
#define IDC_EDIT_DATAPATH               2007
#define IDC_Arrow                       2008
#define IDC_EDIT3                       2009
#define IDC_SIZE_ALL                    2010
#define IDC_EXTENT_LEFT                 2011
#define IDC_SIZE_LEFTRIGHT              2012
#define IDC_EXTENT_TOP                  2013
#define IDC_RASTERLOC                   2014
#define IDC_SIZE_LEFTTOP                2015
#define IDC_EXTENT_RIGHT                2016
#define IDC_COMBO_ORIIMG                2017
#define IDC_SIZE_RIGHTTOP               2018
#define IDC_EXTENT_TOP2                 2019
#define IDC_EXTENT_BOTTOM               2020
#define IDC_EDIT_CLASSVALUE             2020
#define IDC_COMBO_DESTIMG               2021
#define IDC_COMBO_SELCLS_VALUE          2021
#define IDC_SIZE_TOPBOTTOM              2022
#define IDC_BUTTON2                     2022
#define IDC_BTN_COLORPICK               2022
#define IDC_EDIT1                       2023
#define IDC_ON_VERTIX                   2024
#define IDC_EDIT_RELSHP                 2025
#define IDC_VERTIX_MOVE                 2026
#define IDC_BTN_SELCHASHP               2027
#define IDB_MAP_TREE                    2028
#define IDC_CHECK_USEHIS                2029
#define IDB_MAPTREE_STATE               2030
#define IDD_DIALOG_RASTER2VECTOR        2030
#define IDC_CHECK_LOADCHANGE            2031
#define IDD_DLG_MODIFYIMGCLASS          2031
#define IDD_PROGRESS_BAR                2032
#define IDC_EDIT2                       2033
#define IDC_EDIT_CLSNAME                2033
#define IDC_EDIT_CHANGETHD              2034
#define IDC_BUTTON1                     2035
#define IDC_BT_SELCLASSFILE             2035
#define IDC_BUTTON_POLYGON              2036
#define IDC_BTN_SHOWSYMBOL              2037
#define IDR_LAYER_MENU                  2038
#define IDC_EDIT_MINAREA                2039
#define IDD_LAYERPROP_GENERAL           2040
#define IDC_EDIT_MINAREA2               2041
#define IDC_EDIT_TOLL                   2042
#define IDC_COMBO1                      2043
#define IDC_COMBO_SELCLS_FILE           2043
#define IDC_COMBO_RS_LYR                2044
#define IDD_RASTER_PROP                 2045
#define IDC_EDIT_EXWATERSHP             2046
#define IDD_IMG_CHANGEDETECT            2047
#define IDC_BTN_SELEXSHP                2048
#define IDD_OBJ_EXPORT                  2049
#define IDC_BTN_CHASYMBOL               2050
#define IDD_DISTILL_STEP1               2051
#define IDD_DISTILL_STEP2               2052
#define IDI_STEP2                       2053
#define IDI_ICON2                       2054
#define IDI_STEP1                       2055
#define IDD_SET_CHANSYMBOL              2056
#define IDC_Measure                     2057
#define IDC_HANDLE                      2058
#define IDC_HAND                        2059
#define IDD_FEATURE_RENDER_SET          4024
#define IDB_FEATURE_RENDER              4025
#define IDB_RENDER_BG                   4026
#define IDD_SIMPLE_RENDER               4027
#define IDD_SYMBOLSEL_DLG               4028
#define IDD_SYMBOLEDIT_DIALOG           4029
#define IDD_CHARSELECTDLG               4030
#define IDD_DASHARRAYDLG                4031
#define IDB_STATE                       4032
#define IDB_ADD                         4033
#define IDB_COPY                        4034
#define IDB_DEL                         4035
#define IDB_DOWN                        4036
#define IDB_PASTE                       4037
#define IDB_UP                          4038
#define IDB_FEATURE_RENDER1             4039
#define IDB_RENDER_BG1                  4040
#define IDD_SYMBOL_PREVIEW_PAGE         4048
#define IDD_PAGE_ELEMENT_SIZE_POS       5001
#define IDC_TEXT_SYMBOL_PREVIEW         5002
#define IDC_TEXT_SYMBOLSET              5003
#define IDC_CHK_WH_RATIO                5004
#define IDC_CHECK_DRAW_BG               5005
#define IDC_SR_PREVIEW                  5010
#define IDC_SR_SYMBOLSET                5011
#define IDC_RENDER_PAGE_CONTAINER       5012
#define IDC_ADD_SYMBOLLIB               5013
#define IDC_BTN_OVERVIEW                5014
#define IDC_BTN_SYMBOL_EDIT             5015
#define IDC_SYMKEY                      5016
#define IDC_SYMBOLFIND                  5017
#define IDC_SAVESYMBOL                  5018
#define IDC_SYMNAME                     5019
#define IDC_LIST_SYMBOL                 5020
#define IDC_SYMBOLRESETTING             5021
#define IDC_PROPLIST                    5024
#define IDC_COMBO_SYMTYPE               5025
#define IDC_SYMBOLVIEW                  5026
#define IDC_ZOOMFIX                     5027
#define IDC_ZOOM                        5028
#define IDC_REDUCE                      5029
#define IDC_BLOWUP                      5030
#define IDC_ADD                         5031
#define IDC_DEL                         5032
#define IDC_MOVEUP                      5033
#define IDC_MOVEDOWN                    5034
#define IDC_COPY                        5035
#define IDC_PASTE                       5036
#define IDC_CROSSLINE                   5037
#define IDC_DISPLAY                     5038
#define IDC_COMBOUNITS                  5039
#define IDC_STATIC_SYMBOLPROP           5040
#define IDC_CR_LINE                     5041
#define IDC_STR_LINE                    5042
#define IDC_PROPLISTDASHARRAY           5043
#define IDC_BUTTONADD                   5044
#define IDC_BUTTONRMV                   5045
#define IDC_STATICUNIT                  5046
#define IDD_RANGE_RENDER                5050
#define IDC_COMBO_RANGE_FIELD           5051
#define IDC_EDIT_RANGE_NUM              5053
#define IDC_RANGE_NUM_SPIN              5054
#define IDC_BTN_AUTO_SETRANGE           5055
#define IDC_RANGE_SYMBOL_LIST           5056
#define IDC_RG_START_COLOR              5058
#define IDC_RG_END_COLOR                5059
#define IDD_MODIFY_UNIQUE_CLASS         5060
#define IDC_VALUE_LABEL                 5061
#define IDC_EDIT_UNIVALUE               5062
#define IDC_EDIT_UNILABEL               5063
#define IDC_BTN_UNIOV                   5064
#define IDD_ADD_CLASSES                 5076
#define IDC_LIST_ALLVALUES              5077
#define IDC_LIST_SELECTVALUE            5078
#define IDC_ADDSELECT                   5079
#define IDC_ADDALL_VALUE                5080
#define IDC_REMOVE_SELECT               5081
#define IDC_REMOVEALL_VALUE             5082
#define IDD_UNIQUE_RENDER               5101
#define IDC_EDIT_POS_X                  5102
#define IDC_UNIQUE_SYMBOL_LIST          5103
#define IDC_EDIT_POS_Y                  5104
#define IDC_COMBO_UNIQUE_FIELD          5105
#define IDC_EDIT_WIDTH                  5106
#define IDC_EDIT_HEIGHT                 5107
#define IDC_EDIT_NAME                   5108
#define IDC_UNI_ADDALL                  5109
#define IDC_UNI_ADD                     5110
#define IDC_UNI_REMOVE                  5111
#define IDC_UNI_REMOVEALL               5112
#define IDC_RADIO_LEFT_TOP              5113
#define IDC_RADIO_CENTER_TOP            5114
#define IDC_SYMBOL_PREVIEW              5115
#define IDC_RADIO_RIGHT_TOP             5116
#define IDC_SYMBOLSET                   5117
#define IDC_RADIO_LEFT_CENTER           5118
#define IDC_FILL_SYMBOL_PREVIEW         5119
#define IDC_RADIO_CENTER_CENTER         5120
#define IDC_FILL_SYMBOLSET              5121
#define IDC_RADIO_RIGHT_CENTER          5122
#define IDC_RADIO_LEFT_BOTTOM           5123
#define IDC_RADIO_CENTER_BOTTOM         5124
#define IDC_RADIO_RIGHT_BOTTOM          5125
#define IDC_STATIC_UNIT                 5157
#define IDC_STATIC_UNIT2                5158
#define IDC_STATIC_UNIT3                5159
#define IDC_STATIC_UNIT4                5160
#define IDC_BTN_SET_TEXT_SYMBOL         5198
#define IDC_EDIT_MAIN_DIVISION_NUM      5199
#define IDC_SPIN_MAIN_DIVISION_NUM      5200
#define IDD_PAGE_SCALEBAR_UNIT          5200
#define IDD_PAGE_SCALEBAR_MARK          5201
#define IDC_EDIT_SUB_DIVISION_NUM       5202
#define IDC_SPIN_SUB_DIVISION_NUM       5203
#define IDD_PAGE_SCALEBAR_FORMAT        5204
#define IDC_CHK_DIVISION_BF_ZERO        5205
#define IDC_COMBO_UNIT                  5206
#define IDC_COMBO_UNIT_POS              5207
#define IDC_EDITUNIT_GAP                5208
#define IDC_BTN_SET_SYMBOL              5209
#define IDC_CMB_NUM_FREQUENCY           5210
#define IDC_CMB_NUM_POS                 5211
#define IDC_EDIT_NUM_GAP                5212
#define IDC_SPIN_NUM_GAP                5213
#define IDC_CMB_MARK_FREQUENCY          5214
#define IDC_CMB_MARK_POS                5215
#define IDC_EDIT_MAIN_DIVISION_HEIGHT   5216
#define IDC_SPIN_MAIN_DIVISION_HEIGHT   5217
#define IDC_EDIT_SUB_DIVISION_HEIGHT    5218
#define IDC_SPIN_SUB_DIVISION_HEIGHT    5219
#define IDC_BTN_TEXT_SYMBOL             5220
#define IDC_BTN_FORE_FILL_SYMBOL        5221
#define IDC_BTN_BACK_FILL_SYMBOL        5222
#define IDC_CMB_SCALEBAR_STYLE          5223
#define IDC_BTN_MARK_LINE_SYMBOL_PREVIEW 5224
#define IDC_BTN_NUM_TEXT_SYMBOL_PREVIEW 5225
#define IDC_BTN_NUM_SYM_SET             5226
#define IDC_BTN_MARK_SYM_SET            5227
#define IDC_SPIN_UNIT_GAP               5228
#define IDC_BTN_SET_UNIT_SYMBOL         5229
#define IDC_BTN_SET_FORE_FILL_SYMBOL    5230
#define IDC_BTN_SET_FILL_BACK_SYMBOL    5231
#define IDC_COMBO_COLORBAR              5300
#define IDD_PAGE_TEXT_CONTENT           8003
#define IDC_EDIT_TEXT                   8075
#define IDD_TEXT_SYMBOL_PREVIEW_PAGE    9003
#define IDD_TRANSPARENT_ENHANCE         9004
#define IDD_SWIPE_SHOW                  9011
#define ID_32771                        32771
#define ID_ZOOMTO_LAYER                 32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_REMOVE_LAYER                 32775
#define ID_LAYER_PROP                   32776
#define ID_OBJ_EXPORT                   32777
#define ID_SYMBOLRANGSTART              32800
#define ID_SYMBOLRANGEND                32820
#define ID_ADDSYMBOLRANGSTART           32830
#define IDC_SLIDER1                     32831
#define ID_ADDSYMBOLRANGEND             32850
#define IDC_RADIO_UD                    32851
#define IDC_RADIO_LR                    32852
#define IDC_STATIC1                     32853

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2032
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         2023
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
