//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Control.rc
//
#define IDC_PAN                         2000
#define IDC_PROGRESS                    2000
#define IDC_ZOOMIN                      2001
#define IDC_PROGRESS_TITLE              2001
#define IDC_ZOOMOUT                     2002
#define IDC_EDIT_LAYERNAME              2002
#define IDC_Cross                       2003
#define IDC_EDIT_DATAPATH               2003
#define IDC_Arrow                       2004
#define IDC_EDIT3                       2004
#define IDC_SIZE_ALL                    2005
#define IDC_EXTENT_LEFT                 2005
#define IDC_SIZE_LEFTRIGHT              2006
#define IDC_EXTENT_TOP                  2006
#define IDC_RASTERLOC                   2006
#define IDC_SIZE_LEFTTOP                2007
#define IDC_EXTENT_RIGHT                2007
#define IDC_COMBO_ORIIMG                2007
#define IDC_SIZE_RIGHTTOP               2008
#define IDC_EXTENT_TOP2                 2008
#define IDC_EXTENT_BOTTOM               2008
#define IDC_COMBO_DESTIMG               2008
#define IDC_SIZE_TOPBOTTOM              2009
#define IDC_EDIT1                       2009
#define IDC_ON_VERTIX                   2010
#define IDC_EDIT_RELSHP                 2010
#define IDC_VERTIX_MOVE                 2011
#define IDC_BTN_SELCHASHP               2011
#define IDB_MAP_TREE                    2012
#define IDC_CHECK_USEHIS                2012
#define IDB_MAPTREE_STATE               2013
#define IDC_CHECK_LOADCHANGE            2013
#define IDD_PROGRESS_BAR                2014
#define IDC_EDIT2                       2014
#define IDC_EDIT_CHANGETHD              2014
#define IDR_LAYER_MENU                  2015
#define IDD_LAYERPROP_GENERAL           2016
#define IDD_RASTER_PROP                 2017
#define IDD_IMG_CHANGEDETECT            2018
#define IDD_FEATURE_RENDER_SET          4024
#define IDB_FEATURE_RENDER              4025
#define IDB_RENDER_BG                   4026
#define IDD_SIMPLE_RENDER               4027
#define IDD_SYMBOLSEL_DLG               4028
#define IDB_STATE                       4032
#define IDB_ADD                         4033
#define IDB_COPY                        4034
#define IDB_DEL                         4035
#define IDB_DOWN                        4036
#define IDB_PASTE                       4037
#define IDB_UP                          4038
#define IDB_FEATURE_RENDER1             4039
#define IDB_RENDER_BG1                  4040
#define IDD_SYMBOL_PREVIEW_PAGE         4048
#define IDD_PAGE_ELEMENT_SIZE_POS       5002
#define IDC_TEXT_SYMBOL_PREVIEW         5002
#define IDC_TEXT_SYMBOLSET              5003
#define IDC_CHK_WH_RATIO                5004
#define IDC_CHECK_DRAW_BG               5004
#define IDC_SR_PREVIEW                  5010
#define IDC_SR_SYMBOLSET                5011
#define IDC_RENDER_PAGE_CONTAINER       5012
#define IDC_ADD_SYMBOLLIB               5013
#define IDC_BTN_OVERVIEW                5014
#define IDC_BTN_SYMBOL_EDIT             5015
#define IDC_SYMKEY                      5016
#define IDC_SYMBOLFIND                  5017
#define IDC_SAVESYMBOL                  5018
#define IDC_SYMNAME                     5019
#define IDC_LIST_SYMBOL                 5020
#define IDC_SYMBOLRESETTING             5021
#define IDD_RANGE_RENDER                5050
#define IDC_COMBO_RANGE_FIELD           5051
#define IDC_EDIT_RANGE_NUM              5053
#define IDC_RANGE_NUM_SPIN              5054
#define IDC_BTN_AUTO_SETRANGE           5055
#define IDC_RANGE_SYMBOL_LIST           5056
#define IDC_RG_START_COLOR              5058
#define IDC_RG_END_COLOR                5059
#define IDD_MODIFY_UNIQUE_CLASS         5060
#define IDC_VALUE_LABEL                 5061
#define IDC_EDIT_UNIVALUE               5062
#define IDC_EDIT_UNILABEL               5063
#define IDC_BTN_UNIOV                   5064
#define IDD_ADD_CLASSES                 5076
#define IDC_LIST_ALLVALUES              5077
#define IDC_LIST_SELECTVALUE            5078
#define IDC_ADDSELECT                   5079
#define IDC_ADDALL_VALUE                5080
#define IDC_REMOVE_SELECT               5081
#define IDC_REMOVEALL_VALUE             5082
#define IDD_UNIQUE_RENDER               5101
#define IDC_EDIT_POS_X                  5102
#define IDC_UNIQUE_SYMBOL_LIST          5102
#define IDC_EDIT_POS_Y                  5103
#define IDC_COMBO_UNIQUE_FIELD          5103
#define IDC_EDIT_WIDTH                  5104
#define IDC_EDIT_HEIGHT                 5105
#define IDC_EDIT_NAME                   5106
#define IDC_UNI_ADDALL                  5106
#define IDC_UNI_ADD                     5107
#define IDC_UNI_REMOVE                  5108
#define IDC_UNI_REMOVEALL               5109
#define IDC_RADIO_LEFT_TOP              5116
#define IDC_RADIO_CENTER_TOP            5117
#define IDC_SYMBOL_PREVIEW              5117
#define IDC_RADIO_RIGHT_TOP             5118
#define IDC_SYMBOLSET                   5118
#define IDC_RADIO_LEFT_CENTER           5119
#define IDC_FILL_SYMBOL_PREVIEW         5119
#define IDC_RADIO_CENTER_CENTER         5120
#define IDC_FILL_SYMBOLSET              5120
#define IDC_RADIO_RIGHT_CENTER          5121
#define IDC_RADIO_LEFT_BOTTOM           5122
#define IDC_RADIO_CENTER_BOTTOM         5123
#define IDC_RADIO_RIGHT_BOTTOM          5124
#define IDC_STATIC_UNIT                 5157
#define IDC_STATIC_UNIT2                5158
#define IDC_STATIC_UNIT3                5159
#define IDC_STATIC_UNIT4                5160
#define IDC_COMBO_COLORBAR              5300
#define IDD_PAGE_TEXT_CONTENT           8003
#define IDC_EDIT_TEXT                   8075
#define IDD_TEXT_SYMBOL_PREVIEW_PAGE    9003
#define IDD_TRANSPARENT_ENHANCE         9004
#define IDD_SWIPE_SHOW                  9011
#define ID_32771                        32771
#define ID_ZOOMTO_LAYER                 32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_REMOVE_LAYER                 32775
#define ID_LAYER_PROP                   32776
#define IDC_SLIDER1                     32850
#define IDC_RADIO_UD                    32851
#define IDC_RADIO_LR                    32852
#define IDC_STATIC1                     32853

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2019
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         2014
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
