//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by otComUI.rc
//
#define IDB_STATE                       4032
#define IDB_ADD                         4033
#define IDB_COPY                        4034
#define IDB_DEL                         4035
#define IDB_DOWN                        4036
#define IDB_PASTE                       4037
#define IDB_UP                          4038
#define IDB_FEATURE_RENDER              4039
#define IDB_BITMAP2                     4040
#define IDB_RENDER_BG                   4040
#define IDD_SYMBOLEDIT_DIALOG           5000
#define IDD_SYMBOLSEL_DLG               5001
#define IDD_CHARSELECTDLG               5002
#define IDD_DASHARRAYDLG                5003
#define IDC_ADD_SYMBOLLIB               5013
#define IDC_BTN_OVERVIEW                5014
#define IDC_BTN_SYMBOL_EDIT             5015
#define IDC_SYMKEY                      5016
#define IDC_SYMBOLFIND                  5017
#define IDC_SAVESYMBOL                  5018
#define IDC_SYMNAME                     5019
#define IDC_LIST_SYMBOL                 5020
#define IDC_SYMBOLRESETTING             5021
#define IDC_PROPLIST                    5024
#define IDC_COMBO_SYMTYPE               5025
#define IDC_SYMBOLVIEW                  5026
#define IDC_ZOOMFIX                     5027
#define IDC_ZOOM                        5028
#define IDC_REDUCE                      5029
#define IDC_BLOWUP                      5030
#define IDC_ADD                         5031
#define IDC_DEL                         5032
#define IDC_MOVEUP                      5033
#define IDC_MOVEDOWN                    5034
#define IDC_COPY                        5035
#define IDC_PASTE                       5036
#define IDC_CROSSLINE                   5037
#define IDC_DISPLAY                     5038
#define IDC_COMBOUNITS                  5039
#define IDC_STATIC_SYMBOLPROP           5040
#define IDC_CR_LINE                     5041
#define IDC_STR_LINE                    5042
#define IDC_PROPLISTDASHARRAY           5043
#define IDC_BUTTONADD                   5044
#define IDC_BUTTONRMV                   5045
#define IDC_STATICUNIT                  5046
#define IDD_SIMPLE_RENDER               5047
#define IDC_SR_PREVIEW                  5048
#define IDC_SR_SYMBOLSET                5049
#define IDD_RANGE_RENDER                5050
#define IDC_COMBO_RANGE_FIELD           5051
#define IDC_EDIT_RANGE_NUM              5053
#define IDC_RANGE_NUM_SPIN              5054
#define IDC_BTN_AUTO_SETRANGE           5055
#define IDC_RANGE_SYMBOL_LIST           5056
#define IDC_RG_START_COLOR              5058
#define IDC_RG_END_COLOR                5059
#define IDD_MODIFY_UNIQUE_CLASS         5060
#define IDC_VALUE_LABEL                 5061
#define IDC_EDIT_UNIVALUE               5062
#define IDC_EDIT_UNILABEL               5063
#define IDC_BTN_UNIOV                   5064
#define IDD_LAYER_COMMON_PROP           5065
#define IDC_LAYERNAME                   5066
#define IDC_LAYERVISIBLE                5067
#define IDC_RADIO_NOSCALE               5068
#define IDC_RADIO_SCALE                 5069
#define IDC_EDITMAX                     5070
#define IDC_EDITMIN                     5071
#define IDC_LAYERDESCRIB                5073
#define IDD_FEATURE_RENDER_SET          5074
#define IDC_RENDER_PAGE_CONTAINER       5075
#define IDD_ADD_CLASSES                 5076
#define IDC_LIST_ALLVALUES              5077
#define IDC_LIST_SELECTVALUE            5078
#define IDC_ADDSELECT                   5079
#define IDC_ADDALL_VALUE                5080
#define IDC_REMOVE_SELECT               5081
#define IDC_REMOVEALL_VALUE             5082
#define IDD_DLG_GEO_COORDINATE          5083
#define IDC_STATIC_ULX                  5084
#define IDC_STATIC_ULY                  5085
#define IDC_LEFTTOP_X                   5086
#define IDC_LEFTTOP_Y                   5087
#define IDC_STATIC_DRX                  5088
#define IDC_STATIC_DRY                  5089
#define IDC_RIGHTBUTTON_X               5090
#define IDC_RIGHTBUTTON_Y               5091
#define IDC_PROJECTTION                 5094
#define IDC_SHOWPROJECT_INF             5096
#define IDD_PAGE_MAP_BASIC_PROPER       5097
#define IDC_COMBO_REF_SCALE             5098
#define IDD_DLG_CUSTOM_SCALE            5099
#define IDC_EDIT_SCALE                  5100
#define IDD_UNIQUE_RENDER               5101
#define IDC_UNIQUE_SYMBOL_LIST          5102
#define IDC_COMBO_UNIQUE_FIELD          5103
#define IDC_UNI_ADDALL                  5106
#define IDC_UNI_ADD                     5107
#define IDC_UNI_REMOVE                  5108
#define IDC_UNI_REMOVEALL               5109
#define IDC_BTN_UNI_SYMBOLSET           5110
#define IDC_BTN_UP                      5111
#define IDC_BTN_DOWN                    5112
#define IDD_DLG_RASLAYER_PROPERTY       5113
#define IDC_CHECK_BACKCOLORTRANS        5114
#define IDC_BTN_SELCOLOR                5115
#define IDC_EDIT_R                      5116
#define IDC_EDIT_G                      5117
#define IDC_EDIT_B                      5118
#define IDC_CHECK_SET                   5119
#define IDC_EDIT_INVALIDVAL             5120
#define IDC_ROWS                        5121
#define IDC_COM_SCOL                    5122
#define IDC_CHANNELCOUNT                5123
#define IDC_COMBO_BANDS                 5124
#define IDC_EDIT_MAX                    5125
#define IDC_EDIT_MIN                    5126
#define IDC_EDIT_Entroy                 5127
#define IDC_EDIT_MEAN                   5128
#define IDC_EDIT_VAR                    5129
#define IDD_PAGE_ELEMENT_FRAME          5140
#define IDC_EDIT_BORDER_X               5141
#define IDC_SPIN_BORDER_X               5142
#define IDC_EDIT_BORDER_Y               5143
#define IDC_SPIN_BORDER_Y               5144
#define IDC_EDIT_BG_X                   5145
#define IDC_SPIN_BG_X                   5146
#define IDC_EDIT_BG_Y                   5147
#define IDC_SPIN_BG_Y                   5148
#define IDC_EDIT_SHADOW_X               5149
#define IDC_SPIN_SHADOW_X               5150
#define IDC_EDIT_SHADOW_Y               5151
#define IDC_SPIN_SHADOW_Y               5152
#define IDC_BORDER_SYMBOLSET            5153
#define IDC_BG_PREVIEW                  5154
#define IDC_BG_SYMBOLSET                5155
#define IDC_SHADOW_PREVIEW              5156
#define IDC_SHADOW_SYMBOLSET            5157
#define IDC_CHK_DRAW_DRAFT              5158
#define IDC_CHK_DRAW_BORDER             5159
#define IDC_CHK_DRAW_BG                 5160
#define IDC_CHK_DRAW_SHADOW             5161
#define IDC_BORDER_PRIVIEW              5162
#define IDD_PAGE_PICTURE_PATH           5170
#define IDC_EDIT_PATH                   5171
#define IDC_BTN_SET_PATH                5172
#define IDD_SYMBOL_PREVIEW_PAGE         5173
#define IDC_SYMBOL_PREVIEW              5174
#define IDC_SYMBOLSET                   5175
#define IDD_PAGE_ELEMENT_SIZE_POS       5176
#define IDC_EDIT_POS_X                  5177
#define IDC_EDIT_POS_Y                  5178
#define IDC_EDIT_WIDTH                  5179
#define IDC_EDIT_HEIGHT                 5180
#define IDC_EDIT_ELE_NAME               5181
#define IDC_RADIO_LEFT_TOP              5182
#define IDC_RADIO_CENTER_TOP            5183
#define IDC_RADIO_RIGHT_TOP             5184
#define IDC_RADIO_LEFT_CENTER           5185
#define IDC_RADIO_CENTER_CENTER         5186
#define IDC_RADIO_RIGHT_CENTER          5187
#define IDC_RADIO_LEFT_BOTTOM           5188
#define IDC_RADIO_CENTER_BOTTOM         5189
#define IDC_RADIO_RIGHT_BOTTOM          5190
#define IDC_STATIC_UNIT                 5191
#define IDC_STATIC_UNIT2                5192
#define IDC_STATIC_UNIT3                5193
#define IDC_STATIC_UNIT4                5194
#define IDD_PAGE_TEXT_CONTENT           5195
#define IDC_EDIT_TEXT                   5196
#define IDD_TEXT_SYMBOL_PREVIEW_PAGE    5197
#define IDC_TEXT_SYMBOL_PREVIEW         5198
#define IDC_TEXT_SYMBOLSET              5199
#define IDC_FILL_SYMBOL_PREVIEW         5200
#define IDC_FILL_SYMBOLSET              5201
#define IDC_CHECK_DRAW_BG               5202
#define IDC_CHK_WH_RATIO                5203
#define IDD_TEXT_SYMBOLEDIT_DIALOG      5210
#define IDC_STATIC_PREVIEW              5211
#define IDC_COMBO1                      5300
#define IDC_COMBO_COLORBAR              5300
#define IDC_X_CELL                      5301
#define IDC_EDIT2                       5302
#define IDC_Y_CELL                      5302
#define ID_SYMBOLRANGSTART              32800
#define ID_SYMBOLRANGEND                32820
#define ID_ADDSYMBOLRANGSTART           32830
#define ID_ADDSYMBOLRANGEND             32850

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4041
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5303
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
