/* Generated by Together */
#include "stdafx.h"
#include "SymbolArray.h"

Display::CSymbolArray::CSymbolArray(){}
Display::CSymbolArray::~CSymbolArray()
{
	if( GetSize() != 0 )
		RemoveAll();
}

int Display::CSymbolArray::GetSize()
{
	return SYSTEM::CArray<ISymbolPtr>::GetSize();
}

Display::ISymbolPtr Display::CSymbolArray::GetAt(int nIndex)
{
	return SYSTEM::CArray<ISymbolPtr>::GetAt( nIndex );
}

void Display::CSymbolArray::SetAt(int nIndex, ISymbolPtr newElement)
{
	return SYSTEM::CArray<ISymbolPtr>::SetAt( nIndex , newElement );
}

int Display::CSymbolArray::Add(ISymbolPtr newElement)
{
	return SYSTEM::CArray<ISymbolPtr>::Add( newElement );
}
